"""Nginx configuration service."""
from __future__ import annotations

import logging
import subprocess
from pathlib import Path
from typing import Any

from jinja2 import Template

logger = logging.getLogger(__name__)


# Nginx configuration template for WordPress sites
NGINX_WORDPRESS_TEMPLATE = """
# WordPress site: {{ site_name }} ({{ domain }})
# PHP version: {{ php_version }}
# Generated by Unified Portal

server {
    listen 80;
    server_name {{ domain }}{% if www_redirect %} www.{{ domain }}{% endif %};

    root /var/www/html/{{ site_name }};
    index index.php index.html index.htm;

    access_log /var/log/nginx/{{ site_name }}_access.log;
    error_log /var/log/nginx/{{ site_name }}_error.log;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Cloudflare HTTPS detection (for proxied sites)
    set $https_forwarded "";
    if ($http_x_forwarded_proto = "https") {
        set $https_forwarded "on";
    }

    # Client max body size (for uploads)
    client_max_body_size {{ max_upload_size | default('64M') }};

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # PHP handling
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php-{{ php_version }}:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS $https_forwarded;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;
        include fastcgi_params;
    }

    # Deny access to sensitive files
    location ~ /\. {
        deny all;
    }

    location ~* /(?:uploads|files)/.*\.php$ {
        deny all;
    }

    # Static file caching
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires max;
        log_not_found off;
        access_log off;
    }
}
"""


class NginxConfigService:
    """Service for managing Nginx configuration.

    Handles configuration file generation, validation, and reloading
    for WordPress sites and other services.
    """

    def __init__(self, config_dir: str = "/etc/nginx/conf.d", nginx_bin: str = "nginx"):
        """Initialize Nginx config service.

        Args:
            config_dir: Nginx configuration directory
            nginx_bin: Path to nginx binary
        """
        self.config_dir = Path(config_dir)
        self.nginx_bin = nginx_bin

    def generate_wordpress_config(
        self,
        site_name: str,
        domain: str,
        php_version: str,
        www_redirect: bool = False,
        max_upload_size: str = "64M",
    ) -> str:
        """Generate Nginx configuration for a WordPress site.

        Args:
            site_name: Site identifier (e.g., kuma8088-main)
            domain: Site domain (e.g., kuma8088.com)
            php_version: PHP version (e.g., 8.1)
            www_redirect: Include www.domain in server_name
            max_upload_size: Maximum upload size (e.g., 64M)

        Returns:
            Generated Nginx configuration string
        """
        template = Template(NGINX_WORDPRESS_TEMPLATE)
        return template.render(
            site_name=site_name,
            domain=domain,
            php_version=php_version,
            www_redirect=www_redirect,
            max_upload_size=max_upload_size,
        )

    def write_config(self, filename: str, content: str) -> Path:
        """Write Nginx configuration to file.

        Args:
            filename: Configuration filename (e.g., kuma8088-main.conf)
            content: Configuration content

        Returns:
            Path to written configuration file
        """
        config_path = self.config_dir / filename

        try:
            config_path.parent.mkdir(parents=True, exist_ok=True)
            config_path.write_text(content, encoding="utf-8")
            logger.info(f"Nginx configuration written: {config_path}")
            return config_path
        except Exception as e:
            logger.error(f"Failed to write Nginx config: {e}")
            raise IOError(f"Failed to write Nginx configuration: {e}")

    def delete_config(self, filename: str) -> None:
        """Delete Nginx configuration file.

        Args:
            filename: Configuration filename
        """
        config_path = self.config_dir / filename

        try:
            if config_path.exists():
                config_path.unlink()
                logger.info(f"Nginx configuration deleted: {config_path}")
        except Exception as e:
            logger.error(f"Failed to delete Nginx config: {e}")
            raise IOError(f"Failed to delete Nginx configuration: {e}")

    def test_config(self) -> bool:
        """Test Nginx configuration validity.

        Returns:
            True if configuration is valid, False otherwise
        """
        try:
            result = subprocess.run(
                [self.nginx_bin, "-t"],
                capture_output=True,
                text=True,
                timeout=10,
            )

            if result.returncode == 0:
                logger.info("Nginx configuration test successful")
                return True
            else:
                logger.error(f"Nginx configuration test failed: {result.stderr}")
                return False
        except subprocess.TimeoutExpired:
            logger.error("Nginx configuration test timed out")
            return False
        except Exception as e:
            logger.error(f"Nginx configuration test error: {e}")
            return False

    def reload(self) -> bool:
        """Reload Nginx configuration.

        Returns:
            True if reload successful, False otherwise
        """
        try:
            result = subprocess.run(
                [self.nginx_bin, "-s", "reload"],
                capture_output=True,
                text=True,
                timeout=10,
            )

            if result.returncode == 0:
                logger.info("Nginx reloaded successfully")
                return True
            else:
                logger.error(f"Nginx reload failed: {result.stderr}")
                return False
        except subprocess.TimeoutExpired:
            logger.error("Nginx reload timed out")
            return False
        except Exception as e:
            logger.error(f"Nginx reload error: {e}")
            return False

    def create_wordpress_site_config(
        self,
        site_name: str,
        domain: str,
        php_version: str,
        **kwargs: Any,
    ) -> Path:
        """Create and deploy WordPress site Nginx configuration.

        Args:
            site_name: Site identifier
            domain: Site domain
            php_version: PHP version
            **kwargs: Additional template variables

        Returns:
            Path to created configuration file

        Raises:
            IOError: If configuration write fails
            ValueError: If configuration test fails
        """
        # Generate configuration
        config = self.generate_wordpress_config(site_name, domain, php_version, **kwargs)

        # Write configuration
        filename = f"{site_name}.conf"
        config_path = self.write_config(filename, config)

        # Test configuration
        if not self.test_config():
            # Rollback on test failure
            self.delete_config(filename)
            raise ValueError("Nginx configuration test failed, changes rolled back")

        return config_path


# Singleton instance
_nginx_service: NginxConfigService | None = None


def get_nginx_service() -> NginxConfigService:
    """Get Nginx config service singleton.

    Returns:
        NginxConfigService instance
    """
    global _nginx_service
    if _nginx_service is None:
        _nginx_service = NginxConfigService()
    return _nginx_service
